<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\Review;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ReviewSeeder extends Seeder
{
    const data = [
        ['haysell_id' => '797006',
            'name' => 'Գայանե',
            'review' => 'Շատ գեղեցիկ և որակյալ',
            'rating' => '5',
            'ip' => '',
            'status'=>1],
        ['haysell_id' => '539478',
            'name' => 'Արմինե',
            'review' => 'Շատ գեղեցիկ և հարմարավետ ականջօղեր են',
            'rating' => '5',
            'ip' => '',
            'status'=>1],
        ['haysell_id' => '797006',
            'name' => 'Anna',
            'review' => 'Super',
            'rating' => '5',
            'ip' => '',
            'status'=>1],
        ['haysell_id' => '796071',
            'name' => 'Ashkhen',
            'review' => 'Shat nurb e u geghecik',
            'rating' => '5',
            'ip' => '',
            'status'=>1],
        ['haysell_id' => '796077',
            'name' => 'Hermine',
            'review' => 'Shat geghetsik e',
            'rating' => '5',
            'ip' => '',
            'status'=>1],
        ['haysell_id' => '795877',
            'name' => 'Maria',
            'review' => 'Amazing piece of jewelry',
            'rating' => '5',
            'ip' => '',
            'status'=>1],
        ['haysell_id' => '797053',
            'name' => 'Գևորգ',
            'review' => 'Շատ լավն է ոնց կարող եմ պատվիրել',
            'rating' => '4',
            'ip' => '',
            'status'=>1],
        ['haysell_id' => '795340',
            'name' => 'Irina',
            'review' => 'Very nice ring',
            'rating' => '5',
            'ip' => '',
            'status'=>1],
        ['haysell_id' => '510967',
            'name' => 'Լիլիթ',
            'review' => 'Նուրբ և գեղեցիկ ականջօղեր',
            'rating' => '5',
            'ip' => '',
            'status'=>1],
        ['haysell_id' => '796303',
            'name' => 'Աննա',
            'review' => 'Շատ գեղեցիկ են',
            'rating' => '5',
            'ip' => '',
            'status'=>1],
        ['haysell_id' => '510985',
            'name' => 'Mari',
            'review' => 'shat nurb ev geghecik',
            'rating' => '5',
            'ip' => '',
            'status'=>1],
        ['haysell_id' => '795308',
            'name' => 'Կարինե',
            'review' => 'Նվեր եմ ստացել, շատ գեղեցիկ է',
            'rating' => '5',
            'ip' => '',
            'status'=>1],
        ['haysell_id' => '795877',
            'name' => 'Նարինե',
            'review' => 'Պատվիրել եմ կայքում, ուզում եմ ասեմ, որ իրականում շատ ավելի գեղեցիկ է քան նկարում։ Շատ գեղեցիկ փաթեթավորումով եմ ստացել պատվերը։ Առաքումը խոստացված ժամանակին։ Շնորհակալություն',
            'rating' => '5',
            'ip' => '',
            'status'=>1],
        ['haysell_id' => '796292',
            'name' => 'Hasmik',
            'review' => 'Geghecik ev vorakyal zarder, geghecik patetavorum ev arag araqum',
            'rating' => '5',
            'ip' => '',
            'status'=>1],
        ['haysell_id' => '795696',
            'name' => 'Marina',
            'review' => 'Very nice earrings, fast shipping and good service. Thank you ',
            'rating' => '5',
            'ip' => '',
            'status'=>1],
        ['haysell_id' => '795297',
            'name' => 'Галина',
            'review' => 'Очень качественные изделия',
            'rating' => '5',
            'ip' => '',
            'status'=>1],
        ['haysell_id' => '510954',
            'name' => 'Հերմինե',
            'review' => 'Նուրբ և գեղեցիկ ականջօղեր, նվերի հիանալի տարբերակ',
            'rating' => '5',
            'ip' => '',
            'status'=>1],
        ['haysell_id' => '797132',
            'name' => 'Նարինե',
            'review' => 'Շատ գեղեցիկ է',
            'rating' => '5',
            'ip' => '',
            'status'=>1],
        ['haysell_id' => '796447',
            'name' => 'Արմինե',
            'review' => 'Շատ նուրբ և գեղեցիկ ականջօղեր են, իրականում ավելի գեղեցիկ է քան նկարում։ ',
            'rating' => '5',
            'ip' => '',
            'status'=>1],
        ['haysell_id' => '795905',
            'name' => 'Վիկա',
            'review' => 'Բարձրորակ և ժամանակակից զարդեր',
            'rating' => '5',
            'ip' => '',
            'status'=>1],
        ['haysell_id' => '795843',
            'name' => 'Լիլիթ',
            'review' => 'Կախազարդը առաքվեց շատ արագ, շատ գեղեցիկ է և ճաշակով փաթեթավորված',
            'rating' => '5',
            'ip' => '',
            'status'=>1],

    ];

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        foreach (self::data as $data){
           $product = Product::query()->where('haysell_id',$data['haysell_id'])->first();
            if($product){
                Review::query()->create($data);
            }
        }
    }
}
